name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  camera_avfoundation_frame:
    path: ../
  camera_platform_interface_frame: ^2.10.5
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  video_player: ^2.7.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
