name: camera_avfoundation_frame
description: iOS implementation of the camera plugin.
repository: https://github.com/zhukeev/camera_avfoundation_frame
issue_tracker: https://github.com/zhukeev/camera_avfoundation_frame/issues
version: 0.9.20+4

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    implements: camera
    platforms:
      ios:
        pluginClass: CameraPlugin
        dartPluginClass: AVFoundationCamera

dependencies:
  camera_platform_interface_frame: ^2.10.6
  flutter:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any
  mockito: ^5.4.4
  pigeon: ^22.4.2

topics:
  - camera
